### ISSUE TITLE
Lock Faraday version to 0.8 branch

### ISSUE THREAD

**Issue by sgerrand** [stretcher/stretcher#89]
The pessimistic version for the `Faraday` gem is not tight enough in the latest release (v1.21.1) for this gem. As a result, version 0.9.x of `Faraday` gets installed and the gem explodes.

```
$ bundle exec rackup
/Users/s/.gem/ruby/2.2.2/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing': undefined method `load_autoloaded_constants' for #<Faraday::Connection:0x007f897d802218> (NoMethodError)
    from /Users/s/.gem/ruby/2.2.2/gems/stretcher-1.21.1/lib/stretcher.rb:8:in `<top (required)>'
    from /Users/s/src/test/stretcher-1.21.1-app/config.ru:1:in `require'
    from /Users/s/src/test/stretcher-1.21.1-app/config.ru:1:in `block in <main>'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
    from /Users/s/src/test/stretcher-1.21.1-app/config.ru:in `new'
    from /Users/s/src/test/stretcher-1.21.1-app/config.ru:in `<main>'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
    from /Users/s/.gem/ruby/2.2.2/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
    from /Users/s/.gem/ruby/2.2.2/bin/rackup:23:in `load'
    from /Users/s/.gem/ruby/2.2.2/bin/rackup:23:in `<main>'
```

The contents of the two files used:
- `Gemfile`:

``` ruby
source "https://rubygems.org"

gem "rack"
gem "stretcher"
```
- `config.ru`:

``` ruby
require 'stretcher'
```

Fixing this issue should be as simple as applying this diff:

``` diff
     gem.add_runtime_dependency('json')
   end

-  gem.add_dependency('faraday', '~> 0.8')
+  gem.add_dependency('faraday', '~> 0.8.11')
   gem.add_dependency('faraday_middleware', '~> 0.9.0')
   gem.add_dependency('excon', '>= 0.16')
   gem.add_dependency('hashie', '>= 1.2.0')
```

and releasing the change as v1.21.2.

**Comment by sgerrand** [comment]
@andrewvc: I'd be interested in your thoughts on this if and when you have time.

**Comment by sgerrand** [comment]
:wave:

**Comment by andrewvc** [comment]
@sgerrand I currently don't maintain this code anymore, but I've just given you commit rights! If you'd like to release a new gem, just let me know which email address of yours I should add to the gem maintainers list :)
